"""Initial migration

Revision ID: 6b8afa8f9403
Revises: 
Create Date: 2026-05-12 17:01:40.058333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8afa8f9403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MOVIE', 'THEATER', 'CONCERT', name='eventtype', native_enum=False, length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('STANDARD', 'VIP', 'BALCONY', 'PARTERRE', 'LOGE', 'STANDING', name='seattype', native_enum=False, length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_id', 'row_number', 'seat_number', name='unique_seat_in_hall')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('venue_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('has_fixed_seats', sa.Boolean(), nullable=False),
    sa.Column('support_acts', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('age_rating', sa.String(length=10), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('has_subtitles', sa.Boolean(), nullable=False),
    sa.Column('is_3d', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theater_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playwright', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('age_rating', sa.String(length=10), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('cast', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theater_events')
    op.drop_table('movie_events')
    op.drop_table('concert_events')
    op.drop_table('venues')
    op.drop_table('seats')
    op.drop_table('halls')
    op.drop_table('events')
    # ### end Alembic commands ###
